version: '3.8'

services:

  mongo:
    image: mongo:6.0.13-jammy
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db
    networks:
      - workeasy_default

  auth-service:
    build:
      context: ./services/auth-service
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.auth.rule=PathPrefix(`/auth`)"
      - "traefik.http.services.auth.loadbalancer.server.port=3001"
    networks:
      - workeasy_default
    container_name: auth-service
    ports:
      - "3001:3001"
    volumes:
      - ./services/auth-service:/app
    command: npx ts-node-dev --respawn --transpile-only src/app.ts
    env_file:
      - ./services/auth-service/.env
    depends_on:
      - mongo

  company-service:
    build:
      context: ./services/company-services
    container_name: company-service
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.company.rule=PathPrefix(`/api/companies`)"
    - "traefik.http.services.company.loadbalancer.server.port=3000"
   
    networks:
      - workeasy_default
    ports:
      - "3000:3000"
    volumes:
      - ./services/company-services:/app
    command: npx ts-node-dev --respawn --transpile-only src/app.ts
    env_file:
      - ./services/company-services/.env
    depends_on:
      - mongo
  
  traefik:
    image: traefik:v3.0
    command: 
      -  --configFile=/etc/traefik/traefik.yml
    ports:
      - "80:80"
    volumes:
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - workeasy_default


volumes:
  mongo-data:
networks:
    workeasy_default:

