services:

  rabbit-mq:
    image: rabbitmq:3-management
    container_name: rabbit-mq
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 20s
      retries: 5
      start_period: 20s
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: workeasy
      RABBITMQ_DEFAULT_PASS: workeasy123
    user: "0"
    volumes:
      - rabbit-mq-data:/var/lib/rabbitmq

  auth-service:
    build:
      context: ./services/auth-service
      dockerfile: Dockerfile.dev
    container_name: auth-service
    volumes:
      - ./services/auth-service:/app
      - /app/node_modules
    env_file:
      - ./services/auth-service/.env
    depends_on:
      rabbit-mq:
        condition: service_healthy

  company-service:
    build:
      context: ./services/company-services
      dockerfile: Dockerfile.dev
    container_name: company-service
    volumes:
      - ./services/company-services:/app
      - /app/node_modules
    
    env_file:
      - ./services/company-services/.env
    depends_on:
       rabbit-mq:
          condition: service_healthy
    restart: always

  subscription-service:
    build:
      context: ./services/subscription-service
      dockerfile: Dockerfile.dev
    container_name: subscription-service
    volumes:
      - ./services/subscription-service:/app
      - /app/node_modules
    
    env_file:
      - ./services/subscription-service/.env
    depends_on:
      - rabbit-mq
    restart: always

  order-service:
    build:
      context: ./services/order-services
      dockerfile: Dockerfile.dev
    container_name: order-service
    volumes:
      - ./services/order-services:/app
      - /app/node_modules
    env_file:
      - ./services/order-services/.env
    restart: always

  attendence-server:
    build:
      context: ./services/attendence
      dockerfile: Dockerfile.dev
    container_name: attendence-services
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.attendence.rule=PathPrefix(`/api/attendence`)"
      - "traefik.http.routers.attendence.service=attendence"
      - "traefik.http.services.attendence.loadbalancer.server.port=3003"
    volumes:
      - ./services/attendence:/app
      - /app/node_modules
    env_file:
      - ./services/attendence/.env
    depends_on:
      - rabbit-mq

  stock-service:
    build:
      context: ./services/Stockes-service
      dockerfile: Dockerfile.dev
    container_name: stock-service
    volumes:
      - ./services/Stockes-service:/app
      - /app/node_modules
    env_file:
      - ./services/Stockes-service/.env
    


  traefik:
    image: traefik:v3.0
    command:
      - --configFile=/etc/traefik/traefik.yml
    ports:
      - "80:80"
    volumes:
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml
      - ./traefik/directory:/directory
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  rabbit-mq-data:
